name: CI
on: [ "push", "pull_request", "workflow_dispatch"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haxe-version:
          - stable
          - 4.1.5
          - 4.0.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g lix
      - run: lix download
      - run: lix run travix interp
      - run: lix run travix node
